#
# AppVeyor CI Config
#

-
  version: "{branch}.{build}"
  branches:
    only:
      - master
  configuration: Release
  os: Visual Studio 2015
  clone_depth: 1
  build:
    verbosity: minimal
-
  version: "{branch}.{build}"
  branches:
    only:
      - Mosaic
  configuration: Release
  os: Visual Studio 2015
  clone_depth: 1
  build:
    verbosity: minimal
-
  version: unknown.{build}
  configuration: Debug
